import Head from "next/head";
import Layout from "../layouts/Layout";
import { useRouter } from "next/router";
import Chart from "../components/Chart";
export default function Home() {
  const router = useRouter();
  const { pid } = router.query;
  return (
    <>
      <Head>
        <title>{pid}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
    </>
  );
}
